[RFC] Add terminating resistor support
candle-usb/candleLight_fw pull request #108
Opened 2022-09-15 21:10 UTC by Daniel-Trevitz

The mcba_usb kernel driver in linux has support for configurable terminating resistors. This patch adds similar support to this firmware which the gs_usb USB driver would then activate via the netlink interface.

I have not tested this code on the device yet or with the linux driver. Currently, I want to know if the maintainers of candleLight are interested in this functionality.

Once I have tested the kernel module changes against these changes I plan to send a similar RFC for the kernel change.

2022-09-15 21:27 UTC, fenugrec commented
(ref - see ticket #92 as well )

2022-09-16 10:57 UTC, Daniel-Trevitz commented
@marckleinebudde, Have your efforts on this stalled?

2022-09-18 13:28 UTC, marckleinebudde commented
Hello @Daniel-Trevitz,

yes, there was no effort other than the RFC. I'm not sure if @ryedwards build hardware with switchable termination yet. As mentioned in https://github.com/candle-usb/candleLight_fw/issues/92 this should be modeled the same way as the `IDENTIFY` feature. I'll create a patch for the Linux driver implementing these.

2022-09-18 19:16 UTC, Daniel-Trevitz commented
[gs_usb.c.txt](https://github.com/candle-usb/candleLight_fw/files/9595078/gs_usb.c.txt)

@marckleinebudde No need, done and works. Just finished testing.

2022-09-18 20:25 UTC, marckleinebudde commented
Hello @Daniel-Trevitz,

I've made a pseudo PR to review your driver changes:
https://github.com/marckleinebudde/linux/pull/9#pullrequestreview-1111582359

Overloading the `echo_id` is hack and has no cahnce of going mainline. Here's version of the driver patch:

https://lore.kernel.org/all/20220918202348.675850-1-mkl@pengutronix.de

2022-09-18 21:35 UTC, Daniel-Trevitz commented
The revised pull request is not what I am testing with; I have a custom board that uses a neo pixel for status indication.
This is the subset that is relevant to candlelight, with an example added to the dev board for compile testing.

2022-09-19 15:08 UTC, Daniel-Trevitz commented
You want me to roll the difference into the PR?

2022-09-19 15:09 UTC, marckleinebudde commented
Yes, please rebase ontop of my PR.

2022-09-19 16:03 UTC, Daniel-Trevitz commented
Force pushed an update. Still have to rebase off of #109 (learning how to do that...) and actually test it.

2022-09-19 16:04 UTC, Daniel-Trevitz commented on src/gpio.c
> +	(void)state;
gerrrrr

2022-09-19 16:54 UTC, Daniel-Trevitz commented
Testing complete. Changed the dummy implementation in gpio to have fewer ifdefs. I tested by commenting / uncommenting the two new USBD_CtrlError while pretending that the feature was active.

I always get:
sudo ip link set dev can0 type can termination 120
RTNETLINK answers: Broken pipe

2022-09-19 19:46 UTC, marckleinebudde requested changes

2022-09-19 19:46 UTC, marckleinebudde commented on include/gpio.h
> +	term_unsupported = -1,
I personally prefer enums and defines in upper case.

2022-09-19 19:46 UTC, marckleinebudde commented on include/gpio.h
> +
one newline should be enough

2022-09-19 19:46 UTC, marckleinebudde commented on src/gpio.c
> +static int term_state = 0;
no need to initialize static values to zero.

2022-09-19 19:46 UTC, marckleinebudde commented on src/gpio.c
> +enum terminator_status set_term(unsigned int channel, enum terminator_status state)
Can you place them as `static inline` functions into the header file?

2022-09-19 19:46 UTC, marckleinebudde commented on src/usbd_gs_can.c
>  			hcan->last_setup_request = *req;
You can check here with `get_term(req->wValue)` here if that channel supports termination....

2022-09-19 19:46 UTC, marckleinebudde commented on src/gpio.c
> +#ifdef PIN_TERM_Pin
If you move the termination gpio init into a separate function, you can have a `static inline` noop or a proper function.

2022-09-19 19:50 UTC, marckleinebudde commented
> Force pushed an update. Still have to rebase off of #109 (learning how to do that...) and actually test it.

Consider you're on your development branch.

```
# create a backup branch:
git branch backup

# fetch my PR branch into the special branch FETCH_HEAD
git fetch https://github.com/marckleinebudde/candleLight_fw.git termination

# rebase your development branch to FETCH_HEAD
git rebase FETCH_HEAD

# solve conflicts
git add -u
git rebase --continue
```

2022-09-19 19:54 UTC, Daniel-Trevitz commented on include/gpio.h
> +	term_unsupported = -1,
I think I'm not going to change that unless it's required. The existing code is tending to lower case.

2022-09-19 19:56 UTC, marckleinebudde commented on include/gpio.h
> +	term_unsupported = -1,
ok

2022-09-19 19:58 UTC, Daniel-Trevitz commented on src/usbd_gs_can.c
>  			hcan->last_setup_request = *req;
Yeah, that's fair. I had contemplated it, but was tending towards don't do extra work. That said, I think exiting the usb HAL stuff ASAP is better .... and that said I'm probably over thinking this ;)

2022-09-19 19:59 UTC, Daniel-Trevitz commented on src/gpio.c
> +#ifdef PIN_TERM_Pin
ok; I contemplated the same but wanted to follow the existing style.

2022-09-19 20:00 UTC, Daniel-Trevitz commented on src/gpio.c
> +static int term_state = 0;
This was more or less a choice; specifically calling out zero because an alternative implementation could have a termination on by default.

That and I have a hard time trusting that the data is actually nulled... I mean, I know it is... I just don't trust it.

2022-09-19 20:02 UTC, Daniel-Trevitz commented on src/gpio.c
> +enum terminator_status set_term(unsigned int channel, enum terminator_status state)
Do you mean static inline the version that is a nop? I'm not inclined to expose term_state globally.

2022-09-19 20:03 UTC, Daniel-Trevitz commented on src/gpio.c
> +enum terminator_status set_term(unsigned int channel, enum terminator_status state)
That does require we pull config.h into gpio.h. Do we care about header files doing that kind of stuff? I can't imagine we do, but might as well check...

2022-09-19 20:20 UTC, Daniel-Trevitz commented on src/gpio.c
> +#ifdef PIN_TERM_Pin
What'd be better is if we had some kind of isolated board support package solution. I know I'd be interested in upstreaming my neo pixel support, but it's just not possible with the way everything is done with ifdefs. I had to add DMA support, interrupts, activate a different GPIO clock, add a whole new c file, etc. etc.

2022-09-19 21:14 UTC, Daniel-Trevitz commented
> # rebase your development branch to FETCH_HEAD
> git rebase FETCH_HEAD
Ah ha! I was missing this magic FETCH_HEAD. /thankyou/

2022-09-19 21:16 UTC, Daniel-Trevitz commented
I've committed the new version with the rebase; I beleive the static inline of get_term /set_term while in

2022-09-19 21:18 UTC, Daniel-Trevitz commented
I've committed the new version with the rebase; I believe the static inline of get_term /set_term while the termination functionality is disabled addresses your underlying concern; not penalizing performance for something that is unused.

It does not fully inline it, since it would move the data to be a public symbol.

2022-09-20 07:52 UTC, marckleinebudde commented on src/gpio.c
> +static int term_state = 0;
Uninitialized static variables end up in the BSS segment, which is guaranteed by C to be zeroed on startup.

https://stackoverflow.com/questions/9535250/why-is-the-bss-segment-required

2022-10-05 01:07 UTC, fenugrec commented on include/gpio.h
> +	term_unsupported = -1,
> The existing code is tending to lower case.

I had to check - it's true, but the sample size is quite small : ) Stuff in gs_usb.h has uppercase enums and is my preference too, but led.c has lowercase. So whatever.

2022-10-05 01:20 UTC, fenugrec requested changes
Thanks for working on this.

2022-10-05 01:20 UTC, fenugrec commented on src/gpio.c
> +	HAL_GPIO_WritePin(LEDRX_GPIO_Port, LEDRX_Pin, GPIO_INIT_STATE(LEDRX_Active_High));
Ok but this belongs in a separate commit (that would add your GPIO_INIT_STATE macro), as it is not related to terminations

2022-10-05 11:04 UTC, Daniel-Trevitz commented on src/gpio.c
> +	HAL_GPIO_WritePin(LEDRX_GPIO_Port, LEDRX_Pin, GPIO_INIT_STATE(LEDRX_Active_High));
Do you want this change? Do you want it in a separate pull request?

2022-10-05 11:06 UTC, Daniel-Trevitz commented on src/gpio.c
> +	return !!(term_state & (1 << channel));
I doubt the compiler will remove the conditional, but it'll be interesting to check. I'll make the change at some point here.

2022-10-05 12:10 UTC, fenugrec commented on src/gpio.c
> +	return !!(term_state & (1 << channel));
> I doubt the compiler will remove the conditional

Just checked on godbolt.org and it compiles to same code at -O1 and higher (we use -Os) :

```
enum terminator_status get_term(unsigned int channel)
{
	return !!(term_state & (1 << channel));
}


enum terminator_status get_term2(unsigned int channel)
{
	if (term_state & (1 << channel)) {
		return term_active;
	} else {
		return term_inactive;
	}
}
********************************************
get_term:
        ldr     r3, .L2
        ldr     r3, [r3]
        asrs    r3, r3, r0
        movs    r0, r3
        movs    r3, #1
        ands    r0, r3
        bx      lr
.L2:
        .word   .LANCHOR0
get_term2:
        ldr     r3, .L5
        ldr     r3, [r3]
        asrs    r3, r3, r0
        movs    r0, r3
        movs    r3, #1
        ands    r0, r3
        bx      lr
.L5:
```
Therefore I would prefer if you changed it. Thanks !

(Interestingly, c++ doesn't let you cast bool to enum).

2022-10-05 12:11 UTC, fenugrec commented on src/gpio.c
> +	HAL_GPIO_WritePin(LEDRX_GPIO_Port, LEDRX_Pin, GPIO_INIT_STATE(LEDRX_Active_High));
Yes please - one small commit for your GPIO_INIT_STATE changes, then the rest of your changes. I just merged #109 so you would need to rebase anyway I think

2022-10-05 22:10 UTC, closed without merging