Fix the standby pin set/reset to use the active high/low define
candle-usb/candleLight_fw pull request #138
Opened 2022-11-16 23:29 UTC by ryedwards

Code was ignoring the active flag as defined in config.h.  The flag was used in the GPIO init routines but not in can.c where it is used during can_enable and can_disable.

2022-11-16 23:59 UTC, fenugrec requested changes

2022-11-16 23:59 UTC, fenugrec commented on src/can.c
> +	HAL_GPIO_WritePin(nCANSTBY_Port, nCANSTBY_Pin, nCANSTBY_Active_High == 0 ? GPIO_PIN_RESET : GPIO_PIN_RESET);
Umm, this would only ever do GPIO_PIN_RESET ?

Also, we have a macro `GPIO_INIT_STATE` in gpio.c which could be moved to gpio.h and used here FGJ

2022-11-17 17:36 UTC, ryedwards commented on src/can.c
> +	HAL_GPIO_WritePin(nCANSTBY_Port, nCANSTBY_Pin, nCANSTBY_Active_High == 0 ? GPIO_PIN_RESET : GPIO_PIN_RESET);
Agree...not sure what happened here.  Needs to be updated.

2022-11-17 17:44 UTC, ryedwards commented on src/can.c
> +	HAL_GPIO_WritePin(nCANSTBY_Port, nCANSTBY_Pin, nCANSTBY_Active_High == 0 ? GPIO_PIN_RESET : GPIO_PIN_RESET);
Fixed in new commit.

2022-11-17 18:06 UTC, fenugrec commented
Thanks. I rewrote it slightly differently though in f4f1586dbf563b4850d5b52e99aac06f0311403e

2022-11-17 18:06 UTC, closed without merging