Return .user_data section to linker scripts to fix flash saving
candle-usb/candleLight_fw pull request #66
Opened 2021-01-14 11:44 UTC by tuna-f1sh

Developing on my [candleLight fork](https://github.com/tuna-f1sh/candleLight_fw) to add support for USB-PD, I needed to add more settings to flash. Doing this caused me to find that the `.user_data` flash sector has been dropped during the linker script migration. 

Basically, the flash saving of user id is not properly defined at the moment and has the potential to over-write application flash.

This PR ports [this commit from 2016](https://github.com/candle-usb/candleLight_fw/commit/1453d70dc9a9d98ac254893ba5114b8e826e0e39), which reduces the application flash region by 2K and allocates a page for flash memory at the end of the flash area. 

I've also added my [new board](https://github.com/tuna-f1sh/entree) as a supported board. I've love to merge all the code from my master fork into this - is there appetite for that? It does [add quite a few things](https://github.com/candle-usb/candleLight_fw/compare/master...tuna-f1sh:master), including i2c but it's all kept board specific so shouldn't impact other hardware.

2021-02-13 21:47 UTC, fenugrec commented
Whoa, I missed this PR, sorry.

Not sure why that feature was silently dropped  , in https://github.com/candle-usb/candleLight_fw/commit/2ebc665109887bfe95a4ad63ebe5e1d7d13c0fef#diff-579f347859745cf171dd97a898fe970fe0a410e5620b69353887a805eff3c928 ...

It may have something to do with F042 vs F072 memory map differences. Have you compared those ?

Otherwise I agree the current situation can be a problem: as you noticed, .user_data gets linked somewhere in ROM which is clearly not the right thing to do. Just checked a build here and it ends up at 0x080033c8 !

> new board

That depends - 
Extra features applicable to canape only or really out of scope like I2C: sorry, as long as I'm the only one merging stuff, I'll have to decline. If you've looked a bit at the issues and PRs here you'll know I have my plate quite full already trying to test & merge fixes for high-priority, core issues  ...

But if your changes are fixes or clear improvements (like this one), yes, very interested !

2021-02-15 07:08 UTC, tuna-f1sh commented
The PR accounts for the F04 and F07 memory size difference. I think it was probably missed during the change to separate linker files. Anyway, I think it should be good to merge?

No problem re new board, probably best as a fork for now. I'll try to help out with some issues and PRs around here regardless since I can merge any fixes into my fork. I use this firmware almost daily so am happy to help.

2021-02-15 18:11 UTC, fenugrec commented on README.md
> +- Entreé: https://github.com/tuna-f1sh/entree (STM32F042x6)
I'm happy to add this, but could you split in a different commit ?

2021-02-15 18:34 UTC, fenugrec requested changes

2021-02-15 18:34 UTC, fenugrec commented on ldscripts/STM32F072XB.ld
> +  DATA (xrw) : ORIGIN = 0x801f7ff, LENGTH = 2K
why does DATA start at `0x801f7ff`and not `0x0801F800` (page 63) ?

2021-02-15 18:34 UTC, fenugrec commented on ldscripts/STM32F042X6.ld
> +  DATA (xrw) : ORIGIN = 0x8007800, LENGTH = 2K
This would mean 2 pages (F042 has 1kB pages), but `flash_flush()` is hardcoded to erase+write 1 page. Might be simpler /safer to limit the size of the DATA area to 1kB on both 042 and 072 ? That _should_ trigger a linker error if anyone tries to pack more than 1k in there

2021-02-16 07:12 UTC, tuna-f1sh commented on README.md
> +- Entreé: https://github.com/tuna-f1sh/entree (STM32F042x6)
Done.

2021-02-16 07:13 UTC, tuna-f1sh commented on ldscripts/STM32F072XB.ld
> +  DATA (xrw) : ORIGIN = 0x801f7ff, LENGTH = 2K
This was a calculation error on my part - good spot. I've since replace with variables and calculation in file so brought that into this commit instead.

2021-02-16 07:13 UTC, tuna-f1sh commented on ldscripts/STM32F042X6.ld
> +  DATA (xrw) : ORIGIN = 0x8007800, LENGTH = 2K
Ok, I've reduced to 1k NVM area.

2021-02-16 14:23 UTC, fenugrec approved these changes

2021-02-16 16:14 UTC, fenugrec commented
Merged in 05fe629e5c47de8b638a9efd1c662c60862a1be9, thanks !

2021-02-16 16:14 UTC, closed without merging