Misc
candle-usb/candleLight_fw pull request #99
Opened 2022-08-15 21:30 UTC by jhofstee

This includes some cleanup patches, it shouldn't change any functionality.

2022-08-16 11:51 UTC, fenugrec requested changes
generally OK, see inline comments

2022-08-16 11:51 UTC, fenugrec commented on include/util.h
> +	if (!was_enabled)
heh, this could aso be ìf (was_enabled) { enable_irq(); }`  but either way is fine.
But in any case I would insisit on braces { } even if it's just one line.

2022-08-16 12:01 UTC, jhofstee commented on src/interrupts.c
> +static void HardFault_Handler(void)
The ones which are made static are included in the InterruptVectorTable, so that will work fine. Default_Handler is implemented by a symbol (hence it is not made static).

2022-08-16 12:02 UTC, jhofstee commented on include/util.h
> +	if (!was_enabled)
fine with me, I will adjust it.

2022-08-16 14:38 UTC, fenugrec commented on src/interrupts.c
> +static void HardFault_Handler(void)
I'm not sure what the advantage of adding `static` here then ?

2022-08-16 19:40 UTC, jhofstee commented on src/interrupts.c
> +static void HardFault_Handler(void)
It will limit the scope to interrupts.c of which it is an implementation detail. When declared as static other modules cannot accidentally or purposely call it. You can rename / redefine such function inside the compilation what you like, since you are assured it has no external users (well or really lunatic ones)

2022-08-25 08:41 UTC, jhofstee commented on include/util.h
> +	if (!was_enabled)
Done, I was actually waiting for your opinion about the interrupts, feel free to do with that what you want.

2022-08-27 01:41 UTC, fenugrec commented
Hi again, I'm going to merge most of this as-is (still need to think about the static decls for exception handlers), but could you explain this part of the commit reworking `restore_irq()` :

> As a consequence
> interrupts might be re-enabled too early in case of nested disable calls.
> 
> To prevent this, declared enable_irq as void, since it doesn't accept an
> argument

How does declaring enable_irq as `enable_irq(void)` affect nested disable calls ?

At first glance the commit doesn't appear to change functionality, but the message has me wondering now.

2022-08-27 02:06 UTC, fenugrec commented
Merged with changes. Thanks for your patience !

2022-08-27 02:06 UTC, closed without merging